alter function public.set_updated_at() set search_path = public, pg_temp;

create index if not exists idx_store_scan_runs_store_id on public.store_scan_runs (store_id);
create index if not exists idx_card_catalogue_cards_player_id on public.card_catalogue_cards (player_id);
create index if not exists idx_card_catalogue_cards_team_id on public.card_catalogue_cards (team_id);
create index if not exists idx_product_card_matches_checklist_id on public.product_card_matches (checklist_id);
create index if not exists idx_product_card_matches_catalogue_card_id on public.product_card_matches (catalogue_card_id);
create index if not exists idx_product_card_matches_catalogue_variant_id on public.product_card_matches (catalogue_variant_id);
create index if not exists idx_product_card_matches_matched_player_id on public.product_card_matches (matched_player_id);
create index if not exists idx_product_card_matches_reviewed_by on public.product_card_matches (reviewed_by);
create index if not exists idx_watchlist_matches_watchlist_rule_id on public.watchlist_matches (watchlist_rule_id);
create index if not exists idx_watchlist_matches_store_product_id on public.watchlist_matches (store_product_id);
create index if not exists idx_watchlist_matches_product_card_match_id on public.watchlist_matches (product_card_match_id);
create index if not exists idx_watchlist_rules_watchlist_id on public.watchlist_rules (watchlist_id);
create index if not exists idx_watchlist_rules_player_id on public.watchlist_rules (player_id);
create index if not exists idx_watchlist_rules_team_id on public.watchlist_rules (team_id);
create index if not exists idx_watchlist_rules_set_id on public.watchlist_rules (set_id);
create index if not exists idx_match_feedback_store_product_id on public.match_feedback (store_product_id);
create index if not exists idx_match_feedback_product_card_match_id on public.match_feedback (product_card_match_id);
create index if not exists idx_admin_audit_log_admin_user_id on public.admin_audit_log (admin_user_id);

alter table public.stores enable row level security;
alter table public.store_scan_runs enable row level security;
alter table public.store_products enable row level security;
alter table public.source_products enable row level security;
alter table public.product_snapshots enable row level security;
alter table public.players enable row level security;
alter table public.player_aliases enable row level security;
alter table public.teams enable row level security;
alter table public.card_catalogue_sets enable row level security;
alter table public.card_catalogue_cards enable row level security;
alter table public.card_catalogue_variants enable row level security;
alter table public.reference_checklists enable row level security;
alter table public.watchlist enable row level security;
alter table public.listings_feed enable row level security;
alter table public.product_card_matches enable row level security;
alter table public.admin_audit_log enable row level security;
alter table public.scan_runs enable row level security;

drop policy if exists profiles_select_own on public.profiles;
drop policy if exists profiles_update_own on public.profiles;
drop policy if exists watchlists_select_own on public.watchlists;
drop policy if exists watchlists_insert_own on public.watchlists;
drop policy if exists watchlists_update_own on public.watchlists;
drop policy if exists watchlists_delete_own on public.watchlists;
drop policy if exists watchlist_rules_select_own on public.watchlist_rules;
drop policy if exists watchlist_rules_insert_own on public.watchlist_rules;
drop policy if exists watchlist_rules_update_own on public.watchlist_rules;
drop policy if exists watchlist_rules_delete_own on public.watchlist_rules;
drop policy if exists watchlist_matches_select_own on public.watchlist_matches;
drop policy if exists match_feedback_select_own on public.match_feedback;
drop policy if exists match_feedback_insert_own on public.match_feedback;

create policy profiles_select_own on public.profiles for select to authenticated using ((select auth.uid()) = user_id);
create policy profiles_update_own on public.profiles for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy watchlists_select_own on public.watchlists for select to authenticated using ((select auth.uid()) = user_id);
create policy watchlists_insert_own on public.watchlists for insert to authenticated with check ((select auth.uid()) = user_id);
create policy watchlists_update_own on public.watchlists for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy watchlists_delete_own on public.watchlists for delete to authenticated using ((select auth.uid()) = user_id);
create policy watchlist_rules_select_own on public.watchlist_rules for select to authenticated using (exists (select 1 from public.watchlists w where w.id = watchlist_id and w.user_id = (select auth.uid())));
create policy watchlist_rules_insert_own on public.watchlist_rules for insert to authenticated with check (exists (select 1 from public.watchlists w where w.id = watchlist_id and w.user_id = (select auth.uid())));
create policy watchlist_rules_update_own on public.watchlist_rules for update to authenticated using (exists (select 1 from public.watchlists w where w.id = watchlist_id and w.user_id = (select auth.uid()))) with check (exists (select 1 from public.watchlists w where w.id = watchlist_id and w.user_id = (select auth.uid())));
create policy watchlist_rules_delete_own on public.watchlist_rules for delete to authenticated using (exists (select 1 from public.watchlists w where w.id = watchlist_id and w.user_id = (select auth.uid())));
create policy watchlist_matches_select_own on public.watchlist_matches for select to authenticated using (exists (select 1 from public.watchlists w where w.id = watchlist_id and w.user_id = (select auth.uid())));
create policy match_feedback_select_own on public.match_feedback for select to authenticated using ((select auth.uid()) = user_id);
create policy match_feedback_insert_own on public.match_feedback for insert to authenticated with check ((select auth.uid()) = user_id);

create policy players_select_authenticated on public.players for select to authenticated using (true);
create policy player_aliases_select_authenticated on public.player_aliases for select to authenticated using (true);
create policy teams_select_authenticated on public.teams for select to authenticated using (true);
create policy card_catalogue_sets_select_authenticated on public.card_catalogue_sets for select to authenticated using (true);
create policy card_catalogue_cards_select_authenticated on public.card_catalogue_cards for select to authenticated using (true);
create policy card_catalogue_variants_select_authenticated on public.card_catalogue_variants for select to authenticated using (true);
create policy stores_select_authenticated on public.stores for select to authenticated using (true);
create policy store_products_select_authenticated on public.store_products for select to authenticated using (true);
create policy product_card_matches_select_authenticated on public.product_card_matches for select to authenticated using (true);
create policy reference_checklists_select_authenticated on public.reference_checklists for select to authenticated using (true);
create policy listings_feed_select_authenticated on public.listings_feed for select to authenticated using (true);

create policy admin_read_stores on public.store_scan_runs for select to authenticated using (exists (select 1 from public.profiles p where p.user_id = (select auth.uid()) and p.role = 'admin'));
create policy admin_read_source_products on public.source_products for select to authenticated using (exists (select 1 from public.profiles p where p.user_id = (select auth.uid()) and p.role = 'admin'));
create policy admin_read_product_snapshots on public.product_snapshots for select to authenticated using (exists (select 1 from public.profiles p where p.user_id = (select auth.uid()) and p.role = 'admin'));
create policy admin_read_scan_runs on public.scan_runs for select to authenticated using (exists (select 1 from public.profiles p where p.user_id = (select auth.uid()) and p.role = 'admin'));
create policy admin_read_admin_audit_log on public.admin_audit_log for select to authenticated using (exists (select 1 from public.profiles p where p.user_id = (select auth.uid()) and p.role = 'admin'));
create policy admin_read_legacy_watchlist on public.watchlist for select to authenticated using (exists (select 1 from public.profiles p where p.user_id = (select auth.uid()) and p.role = 'admin'));
